version: '2'

services:

    # APP
    nginx:
        build: docker/nginx
        volumes_from:
            - php
        links:
            - php
        depends_on:
            - php

    php:
        build: docker/php
        volumes:
            - ${SYMFONY_APP_PATH}:/symfony:cached
        links:
            - mysql
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3.4-management
        volumes:
          - "hostme_rabbitmq:/var/lib/rabbitmq/mnesia:cached"

    mysql:
        build: docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${SYMFONY_APP_PATH}:/symfony:cached
            - "hostme_mysql:/var/lib/mysql:cached"

volumes:
    hostme_mysql: ~
    hostme_rabbitmq: ~
